In [1]:
import pandas as pd
import numpy as np
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data1' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'key': ['a', 'b' ,'d'],
                        'data2' : np.random.randint(0,10,3)})

print(df_obj1)
print('-'*50)
print(df_obj2)

  key  data1
0   b      6
1   b      1
2   a      6
3   c      5
4   a      8
5   a      2
6   b      1
--------------------------------------------------
  key  data2
0   a      9
1   b      4
2   d      2

In [3]:
# 默认使用相同的列名进行连接，连接的方式是内连接
pd.merge(df_obj1,df_obj2)

  key  data1  data2
0   b      6      4
1   b      1      4
2   a      6      9
3   a      8      9
4   a      2      9
5   b      1      4

In [5]:
# 按照索引值进行连接
pd.merge(df_obj1,df_obj2,left_index=True,right_index=True)

  key_x  data1 key_y  data2
0     b      6     a      9
1     b      1     b      4
2     a      6     d      2

In [6]:
# 左右边均用属性值进行连接
pd.merge(df_obj1,df_obj2,on = 'key')

  key  data1  data2
0   b      6      4
1   b      1      4
2   a      6      9
3   a      8      9
4   a      2      9
5   b      1      4

In [22]:
print(df_obj2)
# 更改列名
df_obj1 = df_obj1.rename(columns={'key':'key1'})
df_obj2 = df_obj2.rename(columns={'keys':'key2'})
print(df_obj1)
print(df_obj2)

  key2  data2
0    a      9
1    b      4
2    d      2
  key1  data1
0    b      6
1    b      1
2    a      6
3    c      5
4    a      8
5    a      2
6    b      1
  key2  data2
0    a      9
1    b      4
2    d      2

In [23]:
# 左表用Key1来连接m右表用Key2来连接
pd.merge(df_obj1,df_obj2,left_on = 'key1',right_on='key2')

  key1  data1 key2  data2
0    b      6    b      4
1    b      1    b      4
2    a      6    a      9
3    a      8    a      9
4    a      2    a      9
5    b      1    b      4

In [24]:
#全外连接类似 与数据库一致
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2', how='outer')  #全外连接

  key1  data1 key2  data2
0    a    6.0    a    9.0
1    a    8.0    a    9.0
2    a    2.0    a    9.0
3    b    6.0    b    4.0
4    b    1.0    b    4.0
5    b    1.0    b    4.0
6    c    5.0  NaN    NaN
7  NaN    NaN    d    2.0

In [25]:
#left join 等价于 left  join
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2', how='left')

  key1  data1 key2  data2
0    b      6    b    4.0
1    b      1    b    4.0
2    a      6    a    9.0
3    c      5  NaN    NaN
4    a      8    a    9.0
5    a      2    a    9.0
6    b      1    b    4.0

In [26]:
# right等价于数据库的right join
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2', how='right')

  key1  data1 key2  data2
0    a    6.0    a      9
1    a    8.0    a      9
2    a    2.0    a      9
3    b    6.0    b      4
4    b    1.0    b      4
5    b    1.0    b      4
6  NaN    NaN    d      2

In [27]:
# 处理重复列名
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                        'data' : np.random.randint(0,10,3)})
#给相同的数据列添加后缀
print(pd.merge(df_obj1, df_obj2, on='key', suffixes=('_left', '_right')))

  key  data_left  data_right
0   b          7           5
1   b          7           5
2   a          7           4
3   a          1           4
4   a          8           4
5   b          8           5

In [28]:
# 按索引连接
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data1' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'data2' : np.random.randint(0,10,3)}, index=['a', 'b', 'd'])
print(df_obj1)
print(df_obj2)

  key  data1
0   b      2
1   b      0
2   a      2
3   c      0
4   a      6
5   a      4
6   b      9
   data2
a      3
b      7
d      3

In [30]:
# right_index的作用是按照右边的索引index作为连接键
print(pd.merge(df_obj1, df_obj2, left_on='key', right_index=True))

  key  data1  data2
0   b      2      7
1   b      0      7
2   a      2      3
4   a      6      3
5   a      4      3
6   b      9      7

In [31]:
pd.merge(df_obj2,df_obj1, left_index=True, right_on='key')

   data2 key  data1
2      3   a      2
4      3   a      6
5      3   a      4
0      7   b      2
1      7   b      0
6      7   b      9